package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;


public class AddContactsTests extends TestBase{

  @Test
  public void addsContactsTestsTest() {
    goToContactPage();
    fillContactForm(new ContactData("Volodya", "Volopas", "404040", "volopas@volo.ru"));
    submitContactsForm();
    goToStartPage();
  }

}


