package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import java.util.concurrent.TimeUnit;


public class AddsContactsTests {
  FirefoxDriver wd;

  @BeforeMethod
  public void setUp() throws Exception{
    wd = new FirefoxDriver();
    wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    wd.get("http://localhost:8080/addressbook/");
    login("admin", "secret");
  }

  private void login(String login, String password) {
    wd.findElement(By.name("user")).click();
    wd.findElement(By.name("user")).sendKeys(login);
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys(password);
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @Test
  public void addsContactsTestsTest() {
    goToContactPage();
    fillContactForm(new ContactData("Volodya", "Volopas", "404040", "volopas@volo.ru"));
    submitContactsForm();
    goToStartPage();
  }

  private void goToContactPage() {
    wd.findElement(By.linkText("add new")).click();
  }
  private void fillContactForm(ContactData contactData) {
    wd.findElement(By.name("firstname")).click();
    wd.findElement(By.name("firstname")).sendKeys(contactData.getFirstname());
    wd.findElement(By.name("lastname")).click();
    wd.findElement(By.name("lastname")).sendKeys(contactData.getLastname());
    wd.findElement(By.name("home")).click();
    wd.findElement(By.name("home")).sendKeys(contactData.getPhone());
    wd.findElement(By.name("email")).click();
    wd.findElement(By.name("email")).sendKeys(contactData.getEmail());
  }

  private void submitContactsForm() {
    wd.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void goToStartPage() {
    wd.findElement(By.id("content")).click();
  }


  @AfterMethod
  public void tearDown() {
    wd.quit();
  }

  public static boolean isAlertPresent(FirefoxDriver wd){

    try{
      wd.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e){
      return false;
    }

  }


}


