package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.ContactData;


public class AddContactsTests extends TestBase {

  @Test
  public void addsContactsTestsTest() {
    app.getContactHelper().goToContactPage();
    app.getContactHelper().fillContactForm(new ContactData("Volodya", null, "404040", "volopas@volo.ru", "test1"), true);
    app.getContactHelper().submitContactsForm();
    app.getContactHelper().goToStartPage();
  }

}


